#Properties saved on 2024-09-21T22:26:41.566653Z
#Sat Sep 21 22:26:41 UTC 2024
hoodie.compaction.payload.class=org.apache.hudi.metadata.HoodieMetadataPayload
hoodie.table.type=MERGE_ON_READ
hoodie.archivelog.folder=archived
hoodie.timeline.layout.version=1
hoodie.table.checksum=1761752921
hoodie.datasource.write.drop.partition.columns=false
hoodie.table.recordkey.fields=key
hoodie.table.name=my_hudi_table_metadata
hoodie.compaction.record.merger.strategy=eeb8d96f-b1e4-49fd-bbf8-28ac514178e5
hoodie.populate.meta.fields=false
hoodie.table.keygenerator.class=org.apache.hudi.metadata.HoodieTableMetadataKeyGenerator
hoodie.table.base.file.format=HFILE
hoodie.table.version=6
